/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 28/Oct/2020 22:14:37
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/

import React from 'react';
import "react-table/react-table.css";
import { RouteComponentProps } from 'react-router';
import { Link } from 'react-router-dom';
import Tab from 'react-bootstrap/Tab';
import Tabs from 'react-bootstrap/Tabs';
import { ISaveMessage, ISelectValue } from '../GeneralTypes';
import { UserContext } from '../../context/UserContext';

import ContractForm from './ContractForm';

import ContractPayment from './ContractPayment';
import { IPayment } from './ContractTypes';
import ContractTeam from './ContractTeam';
import { ITeam } from './ContractTypes';

import { IContractData } from './ContractTypes';
import { ContractAPI } from './ContractAPI';

import { Popup } from '../Popup';
import Attachment from '../Attachment/Attachment';

interface IState {
    currentData: IContractData;
    contractTypevalues: ISelectValue[],
    Contractstatusvalues: ISelectValue[],
    id: number,

    // popup stuff
    popupStyle: string,
    popupMessage: string,
    popupVisible: boolean;
}

class ContractDetails extends React.Component<RouteComponentProps<{ id?: string }>, IState> {
    static displayName = ContractDetails.name;

    static contextType = UserContext;

    constructor(props: Readonly<RouteComponentProps<{ id?: string }>>) {
        super(props);
        if (this.props.match.params.id && this.props.match.params.id !== "add") {
            this.state =
            {
                id: parseInt(this.props.match.params.id, 10),
                currentData: { 
                    
                    //id: 0, code: "", description: "", title: "", startdate: new Date(), enddate: new Date(), status: "", value: 0.0, paymentInfo: [], modifier: "Unchanged" 
                    id: -1,
                    code: '',
                    title: '',
                    description: '',
                    contractType: '',
                    Contractstatus: '',
                    startDate: new Date(),
                    endDate: new Date(),
                    budget: 0.0,
                    paymentInfo: [],
                    teamInfo: [],

                    modifier: "Unchanged"
                },
                contractTypevalues: [],
                Contractstatusvalues: [],

                popupStyle: "",
                popupMessage: "",
                popupVisible: false
            };
        } else {
            // adding
            this.state =
            {
                id: -1,
                currentData: { 
                    //id: -1, code: "", description: "", title: "", startdate: new Date(), enddate: new Date(), status: "", value: 0.0, paymentInfo: [], modifier: "Added" 
                    id: -1,
                    code: '',
                    title: '',
                    description: '',
                    contractType: '',
                    Contractstatus: '',
                    startDate: new Date(),
                    endDate: new Date(),
                    budget: 0.0,
                    paymentInfo: [],
                    teamInfo: [],

                    modifier: "Added"
                    
                },
                contractTypevalues: [],
                Contractstatusvalues: [],

                popupStyle: "",
                popupMessage: "",
                popupVisible: false
            };

        }
    }

    componentDidMount() {
        // fetch the record
        if (this.state.id !== -1) {
            ContractAPI.loadOneRecord(this.state.id, this.context!.access_token)
                .then((res) => {
                    // Update form values
                    this.setState({
                        currentData: { ...res.dataSubject!, modifier: "Modified" }
                    });
                })
                .catch(e => console.error(e));
        }
        ContractAPI.loadDropdownValues("ContractType", this.context!.access_token)
            .then(res => {
                this.setState({ contractTypevalues: res.data });
            }
            );

        ContractAPI.loadDropdownValues("ContractStatus", this.context!.access_token)
            .then(res => {
                this.setState({ Contractstatusvalues: res.data });
            }
            );

    }

    private saveOneRecord = (subaction: string, record: IContractData) => {
        const action = (record.modifier === "Added") ? "POST" : (record.modifier === "Deleted") ? "DELETE" : "PUT";

        const toSave: ISaveMessage<IContractData> =
        {
            id: record.id,
            action: action,
            dataSubject:
            {
                ...record,
                // don't forget to take the sublists as well:
                                    paymentInfo: this.state.currentData.paymentInfo ,                                     teamInfo: this.state.currentData.teamInfo                             },
            subaction: subaction,
            additionalData: []
        };

        ContractAPI.saveRecord(toSave, this.context!.access_token)
            .then(result => {
                if (result.success) {
                    this.setState({ ...this.state, id: result.dataSubject!.id, currentData: result.dataSubject! })
                    // put a toast here
                    this.setState({ popupVisible: true, popupMessage: "Save result: " + result.message, popupStyle: "success" });
                    //alert("Save result: " + result.message)
                } else {
                    // put a toast here
                    //alert("Save failed " + result.message)
                    this.setState({ popupVisible: true, popupMessage: "Save failed: " + result.message, popupStyle: "danger" });
                }
            }
            )
            .catch(e => this.setState({ popupVisible: true, popupMessage: "Save failed: " + e, popupStyle: "danger" }))
    }

    private updatePaymentline = (values: IPayment, isAdding: boolean, currentIndex?: number) => {
        if (isAdding) {
            let newData = this.state.currentData;

            newData.paymentInfo?.push(values);

            this.setState({ currentData: newData });
        } else {
            if (typeof (currentIndex) === "number" && this.state.currentData.paymentInfo) {
                let newData = this.state.currentData;
                if (newData.paymentInfo) {
                    // if we deleted a newly added element, just remove it from the list
                    if (values.modifier === "Deleted" && values.id === -1) {
                        newData.paymentInfo.splice(currentIndex, 1);
                    } else {
                        newData.paymentInfo[currentIndex] = values;
                    }
                    this.setState({ currentData: newData });
                }
            }
        }
        this.setState({ popupVisible: true, popupMessage: (isAdding ? "Added" : values.modifier) + " Payment line", popupStyle: "info" });
        // alert("updatePaymentline " + (isAdding ? "Added" : values.modifier) + " " + JSON.stringify(this.state.currentData, null, 2));
    }
    private updateTeamline = (values: ITeam, isAdding: boolean, currentIndex?: number) => {
        if (isAdding) {
            let newData = this.state.currentData;

            newData.teamInfo?.push(values);

            this.setState({ currentData: newData });
        } else {
            if (typeof (currentIndex) === "number" && this.state.currentData.teamInfo) {
                let newData = this.state.currentData;
                if (newData.teamInfo) {
                    // if we deleted a newly added element, just remove it from the list
                    if (values.modifier === "Deleted" && values.id === -1) {
                        newData.teamInfo.splice(currentIndex, 1);
                    } else {
                        newData.teamInfo[currentIndex] = values;
                    }
                    this.setState({ currentData: newData });
                }
            }
        }
        this.setState({ popupVisible: true, popupMessage: (isAdding ? "Added" : values.modifier) + " Team line", popupStyle: "info" });
        // alert("updateTeamline " + (isAdding ? "Added" : values.modifier) + " " + JSON.stringify(this.state.currentData, null, 2));
    }

    render() {
        return (
            <React.Fragment>
                <Link to={"/Contract"} className="w3-button w3-light-grey w3-round" title="Back to list">
                    <i className="fa fa-list" ></i>&nbsp;Back to List
                </Link> <hr />
                <Popup visible={this.state.popupVisible} message={this.state.popupMessage} style={this.state.popupStyle} onDismiss={() => { this.setState({ popupVisible: false }) }} />
                <Tabs defaultActiveKey='details' id='detailstab'>
                    <Tab eventKey='details' title='Details'>
                        <ContractForm buttonText="Save" currentData={this.state.currentData} 
                            contractTypevalues={this.state.contractTypevalues}
                            Contractstatusvalues={this.state.Contractstatusvalues}
                            saveAction={this.saveOneRecord} />
                    </Tab>
                    <Tab eventKey="paymenttab" title="Payments">
                        <ContractPayment currentData={this.state.currentData} updatePaymentline = {this.updatePaymentline} />
                    </Tab>
                    <Tab eventKey="teamtab" title="Team members">
                        <ContractTeam currentData={this.state.currentData} updateTeamline = {this.updateTeamline} />
                    </Tab>
                    <Tab eventKey="attachments" title="Attachments">
                        {
                            this.state.id === -1 ? <p>You shoud save the new Contract before adding attachments</p> :
                                <Attachment parentItem='00000000-0000-0000-0000-000000000000' uploadedBy={this.context!.profile.name} />
                        }
                    </Tab>
                </Tabs>
            </React.Fragment>
        );
    }


}

// required to have lazy loading
export default ContractDetails;

