/*
**             ------ IMPORTANT ------
<<<<<<< HEAD
** This file was generated by ZeroCode2 on 01/Oct/2020 22:57:27
=======
** This file was generated by ZeroCode2 on 24/Oct/2020 13:53:09
>>>>>>> 9688682ea239520b67688a5702d077f52b379989
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/

import React from 'react';
import { Formik } from 'formik';
import * as Yup from 'yup';
import { Form, Datepicker, SubmitBtn, Input, Textarea, Select } from 'react-formik-ui'
import { ISelectValue } from '../GeneralTypes';

import { IContractData } from './ContractTypes';

interface IProps {
    currentData: IContractData,
<<<<<<< HEAD
        statusvalues : ISelectValue[], 
        contractTypevalues : ISelectValue[], 
=======
        contractTypevalues : ISelectValue[], 
        Contractstatusvalues : ISelectValue[], 
>>>>>>> 9688682ea239520b67688a5702d077f52b379989
        buttonText: string;
    saveAction: (subaction: string, record: IContractData) => void
}

interface IState {
    isSubmitting: boolean;
}

class ContractForm extends React.Component<IProps, IState> {

    constructor(props: Readonly<IProps>) {
        super(props);
        this.state = { isSubmitting: false };
    }

    render() {
        return (
            <Formik
                initialValues={this.props.currentData as any}
                enableReinitialize={true}
                validationSchema={Yup.object({
                    id: Yup.number()
                        .required('Required')
                    ,
                    code: Yup.string()
                        .max(50, 'Must be 50 characters or less')
                        .required('Required')
                    ,
<<<<<<< HEAD
                    description: Yup.string()
                    ,
                    status: Yup.string()
                        .max(50, 'Must be 50 characters or less')
                        .oneOf([
                        'Planned',
                        'Open',
                        'Closed',
                        'Cancelled',
=======
                    title: Yup.string()
                        .required('Required')
                    ,
                    description: Yup.string()
                    ,
                    contractType: Yup.string()
                        .max(50, 'Must be 50 characters or less')
                        .oneOf([
                        'FixedPrice',  // FixedPrice: 1 - Fixed Price
                        'TandM',  // TandM: 2 - Time & Means
                        'QTM',  // QTM: 3 - Quoted Time & Means
                        'FrameContract',  // FrameContract: 4 - Frame Contract
                        ])
                    ,
                    Contractstatus: Yup.string()
                        .max(50, 'Must be 50 characters or less')
                        .oneOf([
                        'Planned',  // Planned: 
                        'Open',  // Open: 
                        'Closed',  // Closed: 
                        'Cancelled',  // Cancelled: 
>>>>>>> 9688682ea239520b67688a5702d077f52b379989
                        ])
                    ,
                    startDate: Yup.date()
                    ,
                    endDate: Yup.date()
                    ,
                    budget: Yup.number()
<<<<<<< HEAD
                    ,
                    contractType: Yup.string()
                        .max(50, 'Must be 50 characters or less')
                        .oneOf([
                        'FixedPrice',
                        'TandM',
                        'QTM',
                        'FrameContract',
                        ])
=======
>>>>>>> 9688682ea239520b67688a5702d077f52b379989
                })}
                onSubmit={(values, { setSubmitting }) => {
                    this.props.saveAction("Delete", values);
                    setSubmitting(false);
                }}
            >
                <Form mode="themed">
                    <Input name="id" label="ID" disabled />
<<<<<<< HEAD
                    <Input name="ID" label="Unique ID"
                     />
                    <Input name="Code" label="Code"
                     />
                    <Textarea name="Description" label="Description"
                     />
                    <Select name='status' label='Status' options={this.props.statusvalues}
                     />
                    <Input name="Startdate" label="Startdate"
                     />
                    <Input name="Enddate" label="Enddate"
                     />
                    <Input name="Budget" label="Budget" type="number" step="0.01"
                     />
                    <Select name='contractType' label='Contract type' options={this.props.contractTypevalues}
                     />
=======
                <Input name='id' label='ID' disabled />
                <Input name='code' label='Code'  />
                <Textarea name='title' label='Title'  />
                <Textarea name='description' label='Description'  />
                <Select name='contractType' label='Contract type' options={this.props.contractTypevalues} />
                <Select name='Contractstatus' label='Status' options={this.props.Contractstatusvalues} />
                <Datepicker name='startDate' label='Start date'  />
                <Datepicker name='endDate' label='End date'  />
                <Input name='budget' label='Budget' type='number' step='0.01' />
>>>>>>> 9688682ea239520b67688a5702d077f52b379989
                    <hr />
                    <SubmitBtn className="w3-button w3-light-grey w3-round" title={this.props.buttonText + "s this record"} disabled={this.state.isSubmitting}>
                        <i className="fa fa-save" ></i>&nbsp;{this.props.buttonText}
                    </SubmitBtn>
                </Form>
            </Formik>
        );
    }
};
export default ContractForm;

