/*
**             ------ IMPORTANT ------
** This file was generated by ZeroCode2 on 01/Oct/2020 22:57:27
** DO NOT MODIFY IT, as it can be regenerated at any moment.
** If you need this file changed, change the underlying model or its template.
*/

export interface IContractData {

    id: number,
    code: string,
    description: string,
    status: string,
    startDate: Date,
    endDate: Date,
    budget: number,
    contractType: string,
    paymentInfo: IPayment[] | null,

    modifier: "Unchanged" | "Added" | "Modified" | "Deleted"
}

export interface IPayment {
    id : number,
    description : string,
    plannedInvoiceDate : Date,
    actualInvoiceDate : Date,
    amount : number,

    modifier: "Unchanged" | "Added" | "Modified" | "Deleted"
}


